from selenium import webdriver
# driver = webdriver.Chrome(executable_path="C:\chromedriver.exe")
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(executable_path = ChromeDriverManager().install())
driver.maximize_window()
threeclick = "https://3click.com/"
driver.get(threeclick)
# from time import sleep
# sleep(1)
print(driver.title)
print(driver.current_url)
from selenium.webdriver.common.by import By
banner = driver.find_element(By.CLASS_NAME,'banner').click()
print(driver.title)
print(driver.current_url)
driver.back()
flight = driver.find_elements(By.CLASS_NAME, 'nav__item')[0].click()
print(driver.title)
print(driver.current_url)
driver.back()
flight = driver.find_elements(By.CLASS_NAME, 'nav__item')[1].click()
print(driver.title)
print(driver.current_url)
driver.back()
flight = driver.find_elements(By.CLASS_NAME, 'nav__item')[2].click()
print(driver.title)
print(driver.current_url)
driver.back()
flight = driver.find_elements(By.CLASS_NAME, 'nav__item')[3].click()
print(driver.title)
print(driver.current_url)
driver.back()
flight = driver.find_elements(By.CLASS_NAME, 'nav__item')[4].click()
print(driver.title)
print(driver.current_url)